#!/usr/bin/env bash

# To implement this command, edit the "Command implementation" section below. 

# Usage
# -----

# Comments prefixed with `#/` are managed by stubbs.
# The `command` and `usage` comments describe the command
# and show its options.
# 
#/ command: xmlstarlet-rpm:upload: "Upload the RPM to GitHub"
#/ usage: rerun xmlstarlet-rpm:upload [ --release <1>] [ --version <1.3.1>] [ --owner <dtolabs>] [ --repository <xmlstarlet-rpm>] [ --package-name <xmlstarlet>] [ --architecture <$(uname -p)>] [ --distribution-release-version <$(rerun rpm:get-distribution-release-version)>] 

# Load common functions
# ---------------------

# Load the function library for this module.
# This loads rerun functions, too.
. $RERUN_MODULE_DIR/lib/functions.sh upload || { 
  echo >&2 "Failed loading function library." ; exit 1 ; 
}

# Error handling
# ---------------

# This script is designed to _fail-fast_.

# Trap errors and exit. The call to `rerun_die` will print the
# the error message and exit with the error command exit status. 

trap 'rerun_die $? "*** command failed: xmlstarlet-rpm:upload. ***"' ERR

# Run [set] `nounset` to treat unset variables as errors. Set [pipefail]
# so a pipeline return status is the value of the last 
# (rightmost) command to exit with non-zero status.
#
# [set]: http://ss64.com/bash/set.html
# [pipefail]: http://www.gnu.org/software/bash/manual/html_node/Pipelines.html

set -o nounset -o pipefail

# Command variables
# -----------------

# This command script can access the following variables
# declared by `rerun` or by the option parser function.

#/ rerun-variables: RERUN, RERUN_VERSION, RERUN_MODULES, RERUN_MODULE_DIR
#/ option-variables: RELEASE VERSION OWNER REPOSITORY PACKAGE_NAME ARCHITECTURE DISTRIBUTION_RELEASE_VERSION

# The `rerun_options_parse` function processes the command line
# arguments. Each accepted command line flag results in setting 
# one the corresponding option variables.

rerun_options_parse "$@"


# Command implementation
# ----------------------

# - - -
# Put the command implementation here.
# - - -

rerun github:create-download --force true --file ${RERUN_MODULE_DIR}/${PACKAGE_NAME}-${VERSION}-${RELEASE}.el${DISTRIBUTION_RELEASE_VERSION}.${ARCHITECTURE}.rpm --owner ${OWNER} --repository ${REPOSITORY}

# Done. Exit with last command exit status.
exit $?

