# Generated by stubbs:add-option. Do not edit, if using stubbs.
# Created: Fri Dec  7 08:08:24 PST 2012
#
#/ usage: xmlstarlet-rpm:package [ --version <1.3.1>] [ --release <1>] [ --package-name <xmlstarlet>] [ --packager <build@dtosolutions.com>] [ --distribution-release-version <$(rerun rpm:get-distribution-release-version)>] [ --architecture <$(uname -p)>] [ --epel-url <http://dl.fedoraproject.org/pub/epel>] 

# _rerun_options_parse_ - Parse the command arguments and set option variables.
#
#     rerun_options_parse "$@"
#
# Arguments:
#
# * the command options and their arguments
#
# Notes:
# 
# * Sets shell variables for any parsed options.
# * The "-?" help argument prints command usage and will exit 2.
# * Return 0 for successful option parse.
#
rerun_options_parse() {
    
    while [ "$#" -gt 0 ]; do
        OPT="$1"
        case "$OPT" in
            --version) rerun_option_check $# ; VERSION=$2 ; shift ;;
            --release) rerun_option_check $# ; RELEASE=$2 ; shift ;;
            --package-name) rerun_option_check $# ; PACKAGE_NAME=$2 ; shift ;;
            --packager) rerun_option_check $# ; PACKAGER=$2 ; shift ;;
            --distribution-release-version) rerun_option_check $# ; DISTRIBUTION_RELEASE_VERSION=$2 ; shift ;;
            --architecture) rerun_option_check $# ; ARCHITECTURE=$2 ; shift ;;
            --epel-url) rerun_option_check $# ; EPEL_URL=$2 ; shift ;;
            # help option
            -?)
                rerun_option_usage
                exit 2
                ;;
            # end of options, just arguments left
            *)
              break
        esac
        shift
    done

    # Set defaultable options.
    [ -z "$VERSION" ] && VERSION="1.3.1"
    [ -z "$RELEASE" ] && RELEASE="1"
    [ -z "$PACKAGE_NAME" ] && PACKAGE_NAME="xmlstarlet"
    [ -z "$PACKAGER" ] && PACKAGER="build@dtosolutions.com"
    [ -z "$DISTRIBUTION_RELEASE_VERSION" ] && DISTRIBUTION_RELEASE_VERSION="$(rerun rpm:get-distribution-release-version)"
    [ -z "$ARCHITECTURE" ] && ARCHITECTURE="$(uname -p)"
    [ -z "$EPEL_URL" ] && EPEL_URL="http://dl.fedoraproject.org/pub/epel"
    # Check required options are set

    # If option variables are declared exportable, export them.

    #
    return 0
}


# Initialize the options variables to null.
VERSION=
RELEASE=
PACKAGE_NAME=
PACKAGER=
DISTRIBUTION_RELEASE_VERSION=
ARCHITECTURE=
EPEL_URL=


